version: "3.9"

services:
  zssn:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      DB_USER: root
      DB_NAME: zssn_development
      DB_PASSWORD: 123456
      DB_HOST: mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
